### ISSUE TITLE
rhos version piecharts order, width and wrapping on smaller screens

### ISSUE THREAD

**Issue by ssbarnea** [bregman-arie/rhoci#13]
RHOS versions should be listed in DESC order, not ASC because most important ones are the newer ones, not the older ones.

Also the default width  of the piechart does wrap allow only for 6 our of the 7 version on one raw, even if browser is full screen (1280 width). There is a lot of wasted panning space which could be eliminated on order to assure that we fit 7 columns by default.

These two issues create a less than ideal user experience because RHOS 11 and RHOS 12 do endup on different rows. Maybe changing the default order should be enough for the moment, because RHOS 6 would end-up on different raw, which is not a big deal.

**Comment by bregman-arie** [comment]
"RHOS versions should be listed in DESC order, not ASC because most important ones are the newer ones, not the older ones." - I understand why you ask for this but I received many different opinions regarding this.

Basically, here is a summary of the talks I had with QE, CI and Dev regarding this topic:

* Show in the first row the most commonly used releases (OSP 10 first, then OSP 7, ...)
* DESC order of releases (basically what you also ask for) because latest is most important but then also exclude the very last one because it's in development
* ASC order which I choose since I believe it was the most popular one among CI folks where they saw benefit in seeing first the eldest releases that should be 100% free of issues since they are supported for years.

Personally, I prefer the first option.

The only way to satisfy everyone here is to allow drag-and-drop of pie charts and save the order. But CBA shows it's not worth the effort.

I hope it explains why the order is as it is. I'm closing this issue now.
